site_name: biopipen
repo_url: https://github.com/pwwang/biopipen
repo_name: pwwang/biopipen
theme:
    palette:
      primary: blue
    name: 'material'
    # font:
    #   text: 'Ubuntu'
    #   code: 'Ubuntu Mono'
markdown_extensions:
    - markdown.extensions.admonition
    - pymdownx.superfences:
        preserve_tabs: true
    - toc:
        baselevel: 2
plugins:
    - search # necessary for search to work
    - mkapi:
        src_dirs: ['biopipen']
extra_css:
    - style.css
extra_javascript:
    - jquery.js
    - extra.js
nav:
    - 'Home': 'index.md'
    - 'Pipelines':
       - 'Single-cell Metabolic Landscape': pipelines/scrna_metabolic.md
    - 'API': mkapi/api/biopipen
    - 'Change log': 'CHANGELOG.md'
