[plugin_opts]
diagram_theme = "fancy"
report_no_collapse_pgs = true

[ScrnaBasic]
clustering = "unsupervised"
infile = "/example/example.txt"

[ScrnaBasicAnnotation.envs]
hitype_db = "hitypedb_pbmc3k"

[ScrnaBasicPrepareAndQC.envs]
cell_qc = "nFeature_RNA > 200"

[ScrnaBasicScGSEA.envs]
gmtfile = "/example/KEGG_pathways.gmt"
group-by = "CD14M_Sample"
ident-1 = "STIM"
ident-2 = "CTRL"

  [ScrnaBasicScGSEA.envs.cases]
  STIM_vs_CTRL_CD14mono = { }

  [ScrnaBasicScGSEA.envs.mutaters]
  CD14M_Sample = "if_else(seurat_clusters == 'CD14+ Mono', Sample, NA)"