name: CI

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: tests/conda/base.yml
          python-version: 3.9
          auto-activate-base: true
      - name: Install biopipen
        run: |
          for envfile in tests/conda/env_*.yml; do
            bname=$(basename $envfile .yml)
            envname=${bname:4}
            conda env create -f $envfile
            conda run --no-capture-output -n $envname poetry install -E verbose -v
          done
      - name: Download reference data
        run: |
          conda run --no-capture-output -n bio python tests/data/prep_refdata.py
      - name: Run tests
        run: |
          make VERBOSE=1
