name: CI

on: [push]

jobs:

  conda-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - id: set-matrix
        run: |
          matrixstr=""
          for envfile in tests/conda/*.yml; do
            matrixstr="$matrixstr,{\"envname\": \"$(basename envfile .yml)\", \"envfile\": \"$envfile\"}"
          done
          echo "::set-output name=matrix::{\"include\": [${matrixstr:1}]}"

  setup-conda:
    needs: conda-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.conda-matrix.outputs.matrix) }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: ${{ matrix.envname }}
          environment-file: ${{ matrix.envfile }}
          python-version: 3.9
          auto-activate-base: false
      - name: Install biopipen
        run: |
          conda run --no-capture-output -n ${{ matrix.envname }} poetry install -v
      - name: Run tests
        run: |
          make VERBOSE=1
