name: CI

on:
  push:
  release:
    types: [published]

jobs:

  build:
    runs-on: ubuntu-latest
    if: github.event_name != 'release'
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: "3.10"
          auto-update-conda: true
          activate-environment: mybase
          channels: conda-forge,defaults
          # mamba-version: "*"
          miniforge-variant: Mambaforge
      - name: Create conda environments and install biopipen
        run: |
          for envfile in tests/conda/env_*.yml; do
            bname=$(basename $envfile .yml)
            envname=${bname:4}
            echo "::group::Creating environment: $envname"
            mamba env create -f $envfile
            echo "::endgroup::"
            echo "::group::Installing biopipen in environment: $envname"
            # conda run --no-capture-output -n $envname bash tests/conda/patch_poetry.sh
            conda run --no-capture-output -n $envname poetry install -v
            echo "::endgroup::"
          done
      - name: List conda information
        run: |
          conda info
          conda env list
      - name: Cache reference data
        id: cache-reference
        uses: actions/cache@v4
        with:
          path: tests/data/reference
          key: reference-${{ hashFiles('tests/data/prep_reference.py') }}
      - name: Download reference data
        if: steps.cache-reference.outputs.cache-hit != 'true'
        run: |
          conda run --no-capture-output -n biopipen python tests/data/prep_reference.py
      - name: Run tests
        run: |
          make --keep-going all VERBOSE=true

  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python # Set Python version
        uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
      - name: Publish to PyPI
        run: poetry publish --build -u ${{ secrets.PYPI_USER }} -p ${{ secrets.PYPI_PASSWORD }}
        if: success()
